application:
  subdomain: openvpn
  background_task: true
  public_path:
    - /
    - /api
  upstreams:
    - location: /
      backend: http://openvpn:8833/
  ingress:
    - protocol: udp
      port: 1194
      service: openvpn
services:
  openvpn:
    # upstream: czyt/openvpn:v2.1.0
    image: czyt/openvpn:v2.1.0
    netadmin: true
    environment:
      - ADMIN_USERNAME={{ .U.admin_username }}
      - ADMIN_PASSWORD={{ .U.admin_password }}
      - OVPN_GATEWAY={{ .U.enable_openvpn_gateway }}
      - OVPN_SUBNET={{ .U.openvpn_subnet }}
      - OVPN_SUBNET6={{ .U.openvpn_subnet6 }}
    binds:
      - /lzcapp/var/data:/data
      - /etc/localtime:/etc/localtime:ro
